In [1]:
import pandas as pd
import numpy as np
import os

In [12]:
data=pd.read_csv('tmdb-movies.csv')
data.columns

Index(['id', 'imdb_id', 'popularity', 'budget', 'revenue', 'original_title',
       'cast', 'homepage', 'director', 'tagline', 'keywords', 'overview',
       'runtime', 'genres', 'production_companies', 'release_date',
       'vote_count', 'vote_average', 'release_year', 'budget_adj',
       'revenue_adj'],
      dtype='object')

In [5]:
movie=data[['original_title','cast','director','keywords','genres']]

In [6]:
movie.head()

,original_title,cast,director,keywords,genres
0,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,Colin Trevorrow,monster|dna|tyrannosaurus rex|velociraptor|island,Action|Adventure|Science Fiction|Thriller
1,Mad Max: Fury Road,Tom Hardy|Charlize Theron|Hugh Keays-Byrne|Nic...,George Miller,future|chase|post-apocalyptic|dystopia|australia,Action|Adventure|Science Fiction|Thriller
2,Insurgent,Shailene Woodley|Theo James|Kate Winslet|Ansel...,Robert Schwentke,based on novel|revolution|dystopia|sequel|dyst...,Adventure|Science Fiction|Thriller
3,Star Wars: The Force Awakens,Harrison Ford|Mark Hamill|Carrie Fisher|Adam D...,J.J. Abrams,android|spaceship|jedi|space opera|3d,Action|Adventure|Science Fiction|Fantasy
4,Furious 7,Vin Diesel|Paul Walker|Jason Statham|Michelle ...,James Wan,car race|speed|revenge|suspense|car,Action|Crime|Thriller

In [13]:
# Remove null values 
movie=movie.fillna('')

In [8]:
#Remove | from columns cast, director, keywords and genres

columns=['cast','director','keywords','genres']

for i in columns:
    movie[i]=movie[i].str.replace('|',' ')

<ipython-input-8-402e95575e0c>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movie[i]=movie[i].str.replace('|',' ')

In [9]:
movie

,original_title,cast,director,keywords,genres
0,Jurassic World,Chris Pratt Bryce Dallas Howard Irrfan Khan Vi...,Colin Trevorrow,monster dna tyrannosaurus rex velociraptor island,Action Adventure Science Fiction Thriller
1,Mad Max: Fury Road,Tom Hardy Charlize Theron Hugh Keays-Byrne Nic...,George Miller,future chase post-apocalyptic dystopia australia,Action Adventure Science Fiction Thriller
2,Insurgent,Shailene Woodley Theo James Kate Winslet Ansel...,Robert Schwentke,based on novel revolution dystopia sequel dyst...,Adventure Science Fiction Thriller
3,Star Wars: The Force Awakens,Harrison Ford Mark Hamill Carrie Fisher Adam D...,J.J. Abrams,android spaceship jedi space opera 3d,Action Adventure Science Fiction Fantasy
4,Furious 7,Vin Diesel Paul Walker Jason Statham Michelle ...,James Wan,car race speed revenge suspense car,Action Crime Thriller
...,...,...,...,...,...
10861,The Endless Summer,Michael Hynson Robert August Lord 'Tally Ho' B...,Bruce Brown,surfer surfboard surfing,Documentary
10862,Grand Prix,James Garner Eva Marie Saint Yves Montand Tosh...,John Frankenheimer,car race racing formula 1,Action Adventure Drama
10863,Beregis Avtomobilya,Innokentiy Smoktunovskiy Oleg Efremov Georgi Z...,Eldar Ryazanov,car trolley stealing car,Mystery Comedy
10864,"What's Up, Tiger Lily?",Tatsuya Mihashi Akiko Wakabayashi Mie Hama Joh...,Woody Allen,spoof,Action Comedy
10865,Manos: The Hands of Fate,Harold P. Warren Tom Neyman John Reynolds Dian...,Harold P. Warren,fire gun drive sacrifice flashlight,Horror

In [10]:
#lower case all the features
features=['original_title','cast','director','keywords','genres']
for i in features:
    movie[i]=movie[i].str.lower()

<ipython-input-10-701fc07c9c20>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movie[i]=movie[i].str.lower()

In [11]:
movie.head()

,original_title,cast,director,keywords,genres
0,jurassic world,chris pratt bryce dallas howard irrfan khan vi...,colin trevorrow,monster dna tyrannosaurus rex velociraptor island,action adventure science fiction thriller
1,mad max: fury road,tom hardy charlize theron hugh keays-byrne nic...,george miller,future chase post-apocalyptic dystopia australia,action adventure science fiction thriller
2,insurgent,shailene woodley theo james kate winslet ansel...,robert schwentke,based on novel revolution dystopia sequel dyst...,adventure science fiction thriller
3,star wars: the force awakens,harrison ford mark hamill carrie fisher adam d...,j.j. abrams,android spaceship jedi space opera 3d,action adventure science fiction fantasy
4,furious 7,vin diesel paul walker jason statham michelle ...,james wan,car race speed revenge suspense car,action crime thriller
...,...,...,...,...,...
10861,the endless summer,michael hynson robert august lord 'tally ho' b...,bruce brown,surfer surfboard surfing,documentary
10862,grand prix,james garner eva marie saint yves montand tosh...,john frankenheimer,car race racing formula 1,action adventure drama
10863,beregis avtomobilya,innokentiy smoktunovskiy oleg efremov georgi z...,eldar ryazanov,car trolley stealing car,mystery comedy
10864,"what's up, tiger lily?",tatsuya mihashi akiko wakabayashi mie hama joh...,woody allen,spoof,action comedy
10865,manos: the hands of fate,harold p. warren tom neyman john reynolds dian...,harold p. warren,fire gun drive sacrifice flashlight,horror

In [14]:
movie['comb']=movie['keywords']+' '+movie['genres']+' '+movie['director']+' '+movie['cast']

In [18]:
movie.rename(columns={"original_title": "movie_title"},inplace=True)

In [19]:
movie.to_csv('main_data1.csv',index=False)